title: Paco learning blog
author: brahmasky
email: paco.luo@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A quick Jekyll blog for my learning about Github Pages
  
# social links
twitter_username: brahmasky # DO NOT include the @ character, or else the build will fail!
github_username:  brahmasky # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
